# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, "8.3"

source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '~> 2.5.3'
pod 'Facebook-iOS-SDK', '~> 4.0.1'
